version: "3.9"
services:
  api:
    image: edar-api
    container_name: edar-api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: always
    ports:
      - "9999:5000"
    volumes:
      - ./api:/api

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/redis

  worker:
    image: edar-api
    container_name: worker
    restart: always
    depends_on:
      - redis
      - api
    command: rq worker --url redis://redis:6379/0

  rq-dashboard:
    image: eoranged/rq-dashboard:latest
    container_name: rq-dashboard
    ports:
      - "9181:9181"
    depends_on:
      - redis
    restart: always
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
